### ISSUE TITLE
Unable to provision sample addons from the examples directory

### ISSUE THREAD

**Issue by kjaksik** [kyma-project/helm-broker#120]
**Description**

After installing Service Catalog and Helm Broker according to [here](https://github.com/kyma-project/helm-broker/blob/master/docs/installation.md#install-helm-broker-from-chart) i tried provsioning Redis from the sample addons located in the `hack/examples` directory. It failed.

Versions of the software used:
- Kubectl - 1.17.3
- Helm - 3.2.4
- Docker - 19.03
- Kind - 0.8.1

**Expected result**

Redis is provisioned

**Actual result**

Response from `/last_operation`
```
{
  "state": "failed",
  "description": "provisioning failed on error: while installing helm release:
    while installing release from chart with name [hb-redis-micro-kj] in namespace []:
    unable to build kubernetes objects from release manifest:
    unable to recognize \"\":
    no matches for kind \"Deployment\" in version \"extensions/v1beta1\""
}
```

**Steps to reproduce**

1. Follow [this](https://github.com/kyma-project/helm-broker/blob/master/docs/installation.md#install-helm-broker-from-chart) tutorial to install Helm Broker
2. Apply [these](https://github.com/kyma-project/helm-broker/blob/master/hack/examples/sample-addons.yaml) addons
3. Provision the Redis addon on the micro plan
4. Check the status of the operation

**Comment by polskikiel** [comment]
Addons from the example are set to latest version which is deprecated, we need to change it to the version from the last addons release
