### ISSUE TITLE
Helm Broker chart testing

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/helm-broker#23]
**Description**

Currently, there is no any build job which checks the chart. We need to have a chart validation in the build process. First, we need to define how should the verification looks like (only static chart validation or running in Minikube/Kind)

**Reasons**

It is easy to make a bug in the chart and the build is green

**Attachments**

**Comment by mszostok** [comment]
Check the official doc about helm-broker installation, and  implement similar Prow pipeline, i.e.:
- install kind
- install helm broker via `helm install`
- consider some simple validation that app is running properly 

**use the default image defined in chart**
