### ISSUE TITLE
Investigate if we can get rid of the addons version

### ISSUE THREAD

**Issue by mszostok** [kyma-project/helm-broker#60]
**Description**

Currently, we have 3 layers for versioning:
1. repository version which contains sets of addons
2. addons version **<- problematic part**
3. Helm Chart version which is wrapped a given addon

From the beginning, an addon was considered as an abstraction layer over a Helm chart which provides all information required to convert the chart into a Service Class. We added the bundle versions which are a new layer and directly not supported in Service Catalog. 

The most problematic part is that the version of the addon is not used anywhere from the beginning and it's confusing for our users who need to create and maintain the addons repository.

We need to have a clear vision if we need the bundle version at all. If we cannot find any purpose for this versioning then we should deprecate that and remove it in the next version.

**AC:**
- a clear statement for the future of the addons versioning (if we can deprecate that and remove it in the next version)

**Comment by polskikiel** [comment]
Consider if we need versioning for this issue: https://github.com/kyma-project/helm-broker/issues/61

**Comment by PK85** [comment]
Three times stale, closing it. @mszostok please reopen if you want to keep it, but make sure to un-stale that every month.
