### ISSUE TITLE
Proposal for updating instance of created addons to the new version

### ISSUE THREAD

**Issue by mszostok** [kyma-project/helm-broker#61]
**Description**

We need to provide a strategy for updating the instances provisioned from given addons.

Scenario:

0. Register the addons repository in version 1.0
1. Provision addon from repo 1.0
2. Update repo addons to version 2.0
3. Update already created an instance from step 1 to version 2.0

We can consider re-using the Service Catalog functionality for updating already created ServiceInstance.

https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#updating-a-service-instance

**AC**
-  proposal for update strategy for a given addon

**Comment by PK85** [comment]
already stale three times. We will not do that in upcoming releases. Closing.
