### ISSUE TITLE
Memory leak when fetching addons

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/helm-broker#63]
**Description**

On our long-lasting clusters, the Helm-broker sometimes restart because of the memory/goroutines leak.

Check the graphs for the Helm Broker from the nightly cluster:
![image](https://user-images.githubusercontent.com/21159554/70248774-ba2aba00-177b-11ea-84ea-ee4cafd942be.png)

On this cluster, we are adding addons in the loop when executing the tests, the memory leak must be related to it.

**Expected result**

The Helm broker has a stable memory footprint.

**Comment by mszostok** [comment]
Andreas Thaler reported such issue:


>When adding my URL to a fresh cluster: github.com/sap/xf-addons//addons/index.yaml
>It looks like the broker just crashes with OOM

>Next try to configure the URL result in:
>  `{"level":"error","log":{"addon":"marketing-connector-0.1.0","message":"while loading addon: while getting Docs URL for addon marketing-connector: while creating archive '/tmp/docs-marketing-connector-0.1.0.tgz': file already exists: /tmp/docs-marketing-connector-0.1.0.tgz","time":"2020-01-08T14:32:34.012Z"}}`


We need to check why this is not working as this is a **blocker** for using HB with git repo on faros pipelines.
