### ISSUE TITLE
Security vulnerability when using url.Parse

### ISSUE THREAD

**Issue by mszostok** [kyma-project/helm-broker#86]
**Description**

Helm Broker downloads the addon from the given Addon Repo URL which can be specified by our clients. Checkmarx report an issue that this approach can lead to resource exhaustion. We need to decide if that can be mitigated, or we should add logic for sanitizing the given URL.

See: https://github.com/kyma-project/helm-broker/blob/29adb8ec7a63e7f22e15cf096db593c88435dd69/internal/addon/provider/https.go#L34

See:https://github.com/kyma-project/helm-broker/blob/54bb24ad0535d2c2266fd1665040cc98723b990e/internal/addon/provider/factory.go#L57

**Comment by polskikiel** [comment]
Imo we should decide if we can allow for such a risk in case only admin users have write permissions for addons configurations.

**Comment by polskikiel** [comment]
After the discussion about security, we decided to mitigate this issue by just describing it for the standalone Helm Broker users. It's already mitigated in Kyma because only `admin` user can modify AddonsConfigurations, so it's authorized.
