### ISSUE TITLE
Support instance updates

### ISSUE THREAD

**Issue by cbarbian-sap** [kyma-project/helm-broker#91]
**Description**

Looking at 

https://github.com/kyma-project/helm-broker/blob/master/internal/broker/server.go#L145
 
it seems that the broker does not implement service instance updates (via PATCH) as described here:
 
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#updating-a-service-instance
 
(indeed the catalog controller receives a 405 error from the helm-broker, when updating e.g. the parameters of an existing instance).
 
On the other hand, the helm-broker documentation mentions a file ‘update-instance-schema.json‘ in the service plan metadata, which somehow indicates that instance updates are supported in principle.
 
If my understanding is correct, would it be possible to support instance updates (mostly parameter updates would be important for us, plan updates would be rather nice to have) ?

**Comment by PK85** [comment]
No time to work on that issue in the next 6 months. Closing for now.
