### ISSUE TITLE
.Capabilities.KubeVersion.GitVersion not properly populated

### ISSUE THREAD

**Issue by cbarbian-sap** [kyma-project/helm-broker#92]
**Description**

It seems that during the bind template rendering, the helm built-in object
`.Capabilities.KubeVersion.GitVersion` is not properly populated. The observed error message on the binding is:

```
Events:
  Type     Reason          Age                From                                Message
  ----     ------          ----               ----                                -------
  Normal   Binding         70s                service-catalog-controller-manager  The binding is being created asynchronously
  Warning  BindCallFailed  69s (x2 over 69s)  service-catalog-controller-manager  Bind call failed: binding failed on error: while resolving bind data: while rendering bind yaml template: while rendering files: render error in "postgresql/templates/statefulset.yaml": template: postgresql/templates/_helpers.tpl:389:44: executing "postgresql.statefulset.apiVersion" at <.Capabilities.KubeVe...>: can't evaluate field GitVersion in type *version.Info
```

**Steps to reproduce**

Create an addon with a helm chart (e.g. https://github.com/bitnami/charts/tree/master/bitnami/postgresql) which uses the mentioned Capability (in _helpers.tpl?), like
```
{{- if semverCompare ">=1.4-0, <1.7-0" .Capabilities.KubeVersion.GitVersion -}}
```
create an instance, and try to bind to it (using some template in the bind.yaml).

**Comment by PK85** [comment]
Please check with helm3

**Comment by cbarbian-sap** [comment]
It seems this is still an issue. 

I tested  with image eu.gcr.io/kyma-project/pr/helm-broker:PR-109.

First, I created a cluster addon that just dumps the built-in variable `.Capabilities` into a ConfigMap. Expected result: 
  ```
KubeVersion:
  Major: "1"
  Minor: "18"
  Version: v1.18.3
```
So it  seems that `.Capabilities.KubeVersion.Version` is properly populated  by helm-broker during 'normal' rendering.

However binding fails with the error
```
Bind call failed: binding failed on error: while resolving bind data:
        while rendering bind yaml template: while rendering files: template: postgresql/templates/_helpers.tpl:398:58:
        executing "postgresql.statefulset.apiVersion" at <semverCompare "<1.14.0">:
        error calling semverCompare: Invalid Semantic Version
```
The affected part of the `_helpers.tpl` (lines 397+) is:
```
{{- define "postgresql.statefulset.apiVersion" -}}
{{- if trimPrefix "v" .Capabilities.KubeVersion.Version | semverCompare "<1.14.0" -}}
{{- print "apps/v1beta2" -}}
{{- else -}}
{{- print "apps/v1" -}}
{{- end -}}
{{- end -}}
```
When changing this to
```
{{- if default "v9.99.9" .Capabilities.KubeVersion.Version | trimPrefix "v" | semverCompare "<1.14.0" -}}
```
then binding is successful. Which means to me that `.Capabilities` is not properly populated (maybe empty?) during rendering of the bind template.
