### ISSUE TITLE
helm-broker helm release names are too long

### ISSUE THREAD

**Issue by cbarbian-sap** [kyma-project/helm-broker#93]
**Description**

If not specified differently, the helm release name generated by the helm-broker will be 
```
hb-<class>-<plan>-<instance’s external id>
```
 (where the external id – if not explicitly given - will be defaulted by the catalog to a UUID as a string of length 36 (such as 9fc45a8c-15f9-4a27-9fae-dff8a7c2e6de).   
On the other hand many helm charts generate resource names which are prefixed by the release name (which is not an immediate issue because resources names usually can be up to 253 characters long). But in certain situations these names (or even longer values) have to be set as label values (which are restricted to 63 characters). Prominent examples of such labels:
- `statefulset.kubernetes.io/pod-name`
- `controller-revision-hash` (on StatefulSet)

For example the value of the `controller-revision-hash` label of a StatefulSet could look like this
```
hb-<class>-<plan>-<instance's external id>-<statefulset name>-<10 digits>
```
Which would imply that the sum of the lengths of class, plan, and statefulset name cannot be more than 10, which is not realistic.

Clearly there are workarounds:
- Specify the `externalID` of the service instance explicitly at instance creation
- Override the name prefix of the artifacts generated by the chart (with `fullnameOverride` or similar).

However both workarounds are far from being optimal because they cause additional effort on the consumer side. It would be better if helm-broker itself could use shorter helm release names.

**Steps to reproduce**

Just create an addon called `redis` with a plan `default` around the bitnami redis chart (https://github.com/bitnami/charts/tree/master/bitnami/redis), and deploy ...

**Comment by PK85** [comment]
yes, that’s a general problem which comes from combination of k8s names limitations and chart templates and placeholders+something cases . You are right HB helm release is up to 53 chars, but plan name and class name is up to 6 chars and the rest is cut off. Your two workarounds make sense. I think on HB side we would consider to use less chars, like rn: UUID only and save “hb-123456-123456-“ 17 chars.

**Comment by cbarbian-sap** [comment]
It would perhaps already be sufficient (at least helpful) to change the release name pattern in [https://github.com/kyma-project/helm-broker/blob/master/internal/broker/provision.go#L313](https://github.com/kyma-project/helm-broker/blob/master/internal/broker/provision.go#L313) from
```
	releaseName := fmt.Sprintf(
		"hb-%s-%s-%s",
		normalize(string(name)),
		normalize(string(planName)),
		iID)
```
to
```
	releaseName := fmt.Sprintf(
		"hb-%s",
		iID)
```
(which would be 39 chars). Since this is clearly an incompatible change, it should be switchable whether to use the shorter pattern. Maybe the release name pattern as such could be a parameter for helm broker (defaulting to the current behaviour).

**Comment by PK85** [comment]
Closing, we will deprecate helm-broker this year.
